name: DeepCluster++
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9  

  # Development tools
  - pip
  
  # Packages available only via pip
  - pip:
    - pathlib  
    - numpy
    - pandas
    - scipy
    - scikit-learn 
    - torch
    - torchvision
    - torchaudio
    - opencv-python
    - Pillow
    - matplotlib
    - seaborn
    - tqdm 